### ISSUE TITLE
Cypress fails to run via Gulp task

### ISSUE THREAD

**Issue by dotherightthing** [dotherightthing/wpdtrt-plugin-boilerplate#170]
Runs locally via

```
./node_modules/.bin/cypress run --record --key xxx  
```

Fails locally & on Travis via

```
yarn run tests
```

Local:

```
[23:23:02] ========================================
[23:23:02] QA step 1/2:
[23:23:02] => Tests: Cypress
[23:23:02] ----------------------------------------
[23:23:02]  
[23:27:09] 'cypressIo' errored after 4.12 min
[23:27:09] Error: Command failed: ./node_modules/.bin/cypress run --record --key THEKEY

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:466:23)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:466:23)
    at Pipe._handle.close (net.js:606:12)
[23:27:09] 'test' errored after 4.12 min
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[wpdtrt-gallery]  
```

Travis:

```
[11:34:47] ========================================
[11:34:47] QA step 1/2:
[11:34:47] => Tests: Cypress
[11:34:47] ----------------------------------------
[11:34:47]  
[11:34:48] 'cypressIo' errored after 909 ms
[11:34:48] Error: Command failed: ./node_modules/.bin/cypress run --record --key [secure]
    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:466:23)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
[11:34:48] 'default' errored after 19 s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command "yarn run build" exited with 1.
```

**Comment by dotherightthing** [comment]
Fixed Cypress path as it is only comes packaged with the boilerplate.

Build now fails due to failing Cypress test. See #73

**Comment by dotherightthing** [comment]
Cypress now failing on Travis only (wpdtrt-gallery)

**Comment by dotherightthing** [comment]
Moved to https://github.com/dotherightthing/wpdtrt-gallery/issues/74
